version: 0.0
os: linux
files:
  - source:  /
    destination:  /home/ubuntu/app
hooks:
  AfterInstall:
    - location: scripts/chown_app.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_pm2.sh
      runas: ubuntu
